version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.working
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/dodo_payments
      - SERVER_ADDR=0.0.0.0:8080
      - RUST_LOG=info
      # Important: disable SQLx offline mode at runtime
      - SQLX_OFFLINE=false
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./migrations:/app/migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dodo_payments
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
