version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/dodo_payments
      - SERVER_ADDR=0.0.0.0:8080
      - RUST_LOG=info
      - SQLX_OFFLINE=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dodo_payments
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "./health-check.sh", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: ["./wait-for-db.sh", "db", "5432", "/app/dodo-payments"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dodo_payments
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: dodo_payments_postgres_data
